builds:
  - main: def-matcher.go
    binary: def-matcher
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

release:
  github:
    owner: angkeith
    name: zsh-fast-alias-tips
