on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: golang:1.11
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: Run GoReleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: goreleaser/goreleaser-action@v1
